apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: gca
type: Opaque
stringData:
  token-secret: '61F7DCB32DDD1E816FBD88EE1772B'
---
apiVersion: v1
kind: Secret
metadata:
  name: connection-strings
  namespace: gca
type: Opaque
stringData:
  catalog: Host=192.168.99.100;User ID=database;Password=database;Database=catalog;
  shipping: Host=192.168.99.100;User ID=database;Password=database;Database=shipping;
  cart: Host=192.168.99.100;User ID=database;Password=database;Database=cart;
  checkout: Host=192.168.99.100;User ID=database;Password=database;Database=checkout;
