apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gca
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lennartkampshoff/gca-frontend:k8s
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: ENV_CATALOG_URL
            valueFrom:
              configMapKeyRef:
                name: services-config-map
                key: catalogService
          - name: ENV_SHIPPING_URL
            valueFrom:
              configMapKeyRef:
                name: services-config-map
                key: shippingService
          - name: ENV_CART_URL
            valueFrom:
              configMapKeyRef:
                name: services-config-map
                key: cartService
          - name: ENV_CHECKOUT_URL
            valueFrom:
              configMapKeyRef:
                name: services-config-map
                key: checkoutService
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gca
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort