apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels: {{- include "helm.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
  - port: {{ .Values.database.port }}
    targetPort: db
  type: ClusterIP