apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - targetPort: web
    port: 80
    nodePort: {{ .Values.frontend.port }}
  type: NodePort