// <auto-generated />
using System;
using CatalogService.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20220614165142_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cf05588-d2a7-4760-98b1-c464335711a7"),
                            Name = "Ibu 400",
                            Price = 50
                        },
                        new
                        {
                            Id = new Guid("ae66081f-d5c4-468d-96ef-52dc163cea32"),
                            Name = "Ibu 600",
                            Price = 75
                        },
                        new
                        {
                            Id = new Guid("669e6e98-752c-4309-98b6-176aa3c2c8cd"),
                            Name = "Ibu 800",
                            Price = 110
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
