apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-logging
  namespace: gca
spec:
  selector:
    matchLabels:
      app: seq-logging
  template:
    metadata:
      labels:
        app: seq-logging
    spec:
      containers:
      - name: seq-logging
        image: datalust/seq
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
        env:
          - name: ACCEPT_EULA
            value: 'Y'
        ports:
        - containerPort: 5341
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seq-logging-data
  namespace: gca
spec:
  selector:
    app: seq-logging
  ports:
  - port: 5341
    targetPort: 5341
---
apiVersion: v1
kind: Service
metadata:
  name: seq-logging-webui
  namespace: gca
spec:
  selector:
    app: seq-logging
  ports:
  - port: 4000
    targetPort: 80
    nodePort: 30400
  type: NodePort
