apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.connectionStrings.name }}
  labels: {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $.Values.secrets.connectionStrings.values }}
  {{ .key }}: {{ .value }}
  {{- end}}