apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backendSecrets.name }}
  labels: {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.backendSecrets.values }}
  {{ $key }}: {{ . }}
  {{- end}}